#
##root -l -b -q 'MassScan.C("Expected", "TChiSlepV11mtll30", "_TChiSlep", true)'
##root -l -b -q 'MassScan.C("Expected", "TChiSlepV11mtll30mergeveto", "_TChiSlep", true)'
##root -l -b -q 'MassScan.C("Expected", "TChiSlepV11mtll40mergeveto", "_TChiSlep", true)'
##root -l -b -q 'MassScan.C("Expected", "TChiSlepV11mtll40nojetBin215", "_TChiSlep", true)'
##root -l -b -q 'MassScan.C("Expected", "TChiSlepV11mtll40nojetBin215uncorr", "_TChiSlep", true)'
##root -l -b -q 'MassScan.C("Expected", "TChiSlepV11mtll40notag", "_TChiSlep", true)'
##root -l -b -q 'MassScan.C("Expected", "TChiSlepV11mtll40notaguncorr", "_TChiSlep", true)'
root -l -b -q 'MassScan.C("Expected", "TChiSlepV11mtll40Bin215", "_TChiSlep", true)'
root -l -b -q 'MassScan.C("Expected", "TChiSlepV11mtll40Bin215uncorr", "_TChiSlep", true)'
#
##root -l -b -q 'MassScan.C("Blind", "TChiSlepV11mtll30", "_TChiSlep", true)'
##root -l -b -q 'MassScan.C("Blind", "TChiSlepV11mtll30mergeveto", "_TChiSlep", true)'
#root -l -b -q 'MassScan.C("Blind", "TChiSlepV11mtll40mergeveto", "_TChiSlep", true)'
##root -l -b -q 'MassScan.C("Blind", "TChiSlepV11mtll40nojetBin215", "_TChiSlep", true)'
##root -l -b -q 'MassScan.C("Blind", "TChiSlepV11mtll40nojetBin215uncorr", "_TChiSlep", true)'
##root -l -b -q 'MassScan.C("Blind", "TChiSlepV11mtll40notag", "_TChiSlep", true)'
##root -l -b -q 'MassScan.C("Blind", "TChiSlepV11mtll40notaguncorr", "_TChiSlep", true)'
root -l -b -q 'MassScan.C("Blind", "TChiSlepV11mtll40Bin215", "_TChiSlep", true)'
root -l -b -q 'MassScan.C("Blind", "TChiSlepV11mtll40Bin215uncorr", "_TChiSlep", true)'
#